version: '2'
services:
  eurekaserver:
      image: tofikmussa/eurekasvr:assignment2.3
      ports:
        - "8761:8761"
  confsvr:
      image: tofikmussa/confsvr:assignment2.3
      ports:
        - "8888:8888"
      environment:
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        EUREKASERVER_PORT: "8761"
  zuul-service:
      image: tofikmussa/zuulsvr:assignment2.3
      ports:
        - "5555:5555"
      environment:
        PROFILE: "default"
        SERVER_PORT: "5555"
        CONFIGSERVER_URI: "http://confsvr:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        EUREKASERVER_PORT: "8761"
        CONFIGSERVER_PORT:   "8888"
        DATABASESERVER_PORT: "5432"
  database:
      image: postgres:9.5
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "password"
        POSTGRES_DB: "assets_service_db"
  assets-service:
      image: tofikmussa/assets-service:assignment2.3
      ports:
        - "8080:8080"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8080"
        CONFIGSERVER_URI: "http://confsvr:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        EUREKASERVER_PORT: "8761"
        CONFIGSERVER_PORT:   "8888"
        DATABASESERVER_PORT: "5432"
  company-service:
      image: tofikmussa/company-service:assignment2.3
      ports:
        - "8081:8081"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8081"
        CONFIGSERVER_URI: "http://confsvr:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        EUREKASERVER_PORT: "8761"
        CONFIGSERVER_PORT:   "8888"
        DATABASESERVER_PORT: "5432"
  company-service-new:
      image: tofikmussa/company-service-new:assignment2.3
      ports:
        - "8082:8082"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8082"
        CONFIGSERVER_URI: "http://confsvr:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        EUREKASERVER_PORT: "8761"
        CONFIGSERVER_PORT:   "8888"
        DATABASESERVER_PORT: "5432"
  specialroutes-service:
      image: tofikmussa/specialroutes-service:assignment2.3
      ports:
        - "8091:8091"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8091"
        CONFIGSERVER_URI: "http://confsvr:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        EUREKASERVER_PORT: "8761"
        CONFIGSERVER_PORT:   "8888"
        DATABASESERVER_PORT: "5432"
