version: '2'
services:
  eurekaserver:
      image: tofikmussa/eurekasvr:assignment2.1
      ports:
        - "8761:8761"
  confsvr:
      image: tofikmussa/confsvr:assignment2.1
      ports:
        - "8888:8888"
      environment:
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        EUREKASERVER_PORT: "8761"
  database:
      image: postgres:9.5
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "password"
        POSTGRES_DB: "assets_service_db"
  assets-service:
      image: tofikmussa/assets-service:assignment2.1
      ports:
        - "8080:8080"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8080"
        CONFIGSERVER_URI: "http://confsvr:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        EUREKASERVER_PORT: "8761"
        CONFIGSERVER_PORT:   "8888"
        DATABASESERVER_PORT: "5432"
  company-service:
      image: tofikmussa/company-service:assignment2.1
      ports:
        - "8081:8081"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8081"
        CONFIGSERVER_URI: "http://confsvr:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        EUREKASERVER_PORT: "8761"
        CONFIGSERVER_PORT:   "8888"
        DATABASESERVER_PORT: "5432"
  company-service-2:
      image: tofikmussa/company-service:assignment2.1
      ports:
        - "8082:8082"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8082"
        CONFIGSERVER_URI: "http://confsvr:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        EUREKASERVER_PORT: "8761"
        CONFIGSERVER_PORT:   "8888"
        DATABASESERVER_PORT: "5432"
