server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 3
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/
spring:
  application:
    name: eurekasvr
    