eureka:
  instance:
    preferIpAddress: true
    hostname: eurekaserver
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/