server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tmussa1/config-server-repo/
          searchPaths: assets-service, company-service
          ignore-local-ssh-settings: true
      discovery:
        enabled: true
         